name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Prepare signing key
      run: echo $SIGNING_KEY | base64 -d > ../signingKey.snk
    - name: Dotnet build
      run: dotnet build -c Debug
    - name: Dotnet test
      run: dotnet test --no-build -c Debug

